import {app,BrowserWindow,dialog,ipcMain,shell,protocol} from 'electron';
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import Database from 'better-sqlite3';import AdmZip from 'adm-zip';
import type {Project,Asset} from '../shared/model';import {emptyData} from '../shared/model';
let win:BrowserWindow;let db:Database.Database;const root=()=>app.getPath('userData');const projectDir=(id:string)=>path.join(root(),'projects',id);const log=(e:unknown)=>{fs.mkdirSync(root(),{recursive:true});fs.appendFileSync(path.join(root(),'app.log'),`${new Date().toISOString()} ${String(e)}\n`)};
function validId(id:string){if(!/^[a-f0-9-]{36}$/.test(id))throw Error('项目 ID 无效');return id}
function init(){fs.mkdirSync(path.join(root(),'database'),{recursive:true});db=new Database(path.join(root(),'database','app.db'));db.pragma('journal_mode = WAL');db.pragma('foreign_keys = ON');db.exec('CREATE TABLE IF NOT EXISTS schema_version(version INTEGER NOT NULL); INSERT INTO schema_version SELECT 1 WHERE NOT EXISTS(SELECT 1 FROM schema_version); CREATE TABLE IF NOT EXISTS projects(id TEXT PRIMARY KEY,name TEXT NOT NULL,type TEXT,city TEXT,address TEXT,contact TEXT,createdAt TEXT,updatedAt TEXT,status TEXT,data TEXT NOT NULL)');dailyBackup()}
function rowToProject(row:Record<string,unknown>):Project{return {...row,data:JSON.parse(String(row.data))} as Project}
function save(p:Project){validId(p.id);p.updatedAt=new Date().toISOString();db.prepare('INSERT INTO projects(id,name,type,city,address,contact,createdAt,updatedAt,status,data) VALUES(@id,@name,@type,@city,@address,@contact,@createdAt,@updatedAt,@status,@data) ON CONFLICT(id) DO UPDATE SET name=excluded.name,type=excluded.type,city=excluded.city,address=excluded.address,contact=excluded.contact,updatedAt=excluded.updatedAt,status=excluded.status,data=excluded.data').run({...p,data:JSON.stringify(p.data)});return p}
function backups(){const dir=path.join(root(),'backups');fs.mkdirSync(dir,{recursive:true});return dir}
function makeBackup(){const file=path.join(backups(),`app-${new Date().toISOString().replace(/[:.]/g,'-')}.db`);db.backup(file);return file}
function dailyBackup(){const files=fs.readdirSync(backups()).filter(x=>x.endsWith('.db')).sort().reverse();if(!files.some(x=>x.startsWith(`app-${new Date().toISOString().slice(0,10)}`)))void makeBackup();for(const old of files.slice(7))fs.rmSync(path.join(backups(),old))}
function ensureAsset(p:Project,source:string,folder:string):Asset{const ext=path.extname(source).toLowerCase();const allowed:Record<string,string[]>={images:['.jpg','.jpeg','.png','.webp'],attachments:['.pdf','.xls','.xlsx','.doc','.docx','.png','.jpg','.jpeg','.zip'],videos:['.mp4','.mov'],'richtext-assets':['.jpg','.jpeg','.png','.webp']};if(!allowed[folder]?.includes(ext))throw Error('该附件已损坏或格式不受支持');const id=crypto.randomUUID();const rel=`${folder}/${id}${ext}`;const target=path.join(projectDir(p.id),rel);fs.mkdirSync(path.dirname(target),{recursive:true});fs.copyFileSync(source,target);const stat=fs.statSync(target);return {id,name:path.basename(source),relativePath:rel,size:stat.size,mime:ext}}
function assetPath(p:Project,a:Asset){const base=projectDir(validId(p.id));const full=path.resolve(base,a.relativePath);if(!full.startsWith(base+path.sep))throw Error('无效文件路径');return full}
function setup(){const call=(name:string,fn:(...args:any[])=>unknown)=>ipcMain.handle(name,async(_event,...args)=>{try{return await fn(...args)}catch(e){log(e);throw Error(String(e instanceof Error?e.message:e))}});
call('list',()=>db.prepare('SELECT * FROM projects ORDER BY updatedAt DESC').all().map(x=>rowToProject(x as Record<string,unknown>)));
call('save',(p:Project)=>save(p));call('create',()=>{const id=crypto.randomUUID(),now=new Date().toISOString();const p:Project={id,name:'未命名项目',type:'',city:'',address:'',contact:'',createdAt:now,updatedAt:now,status:'编辑中',data:emptyData()};fs.mkdirSync(projectDir(id),{recursive:true});return save(p)});
call('asset:add',async(p:Project,folder:string,paths?:string[])=>{let sources=paths;if(!sources){const result=await dialog.showOpenDialog(win,{properties:['openFile','multiSelections'],filters:[{name:'资料文件',extensions:folder==='images'?['jpg','jpeg','png','webp']:folder==='videos'?['mp4','mov']:['pdf','xls','xlsx','doc','docx','png','jpg','jpeg','zip']}]});if(result.canceled)return [];sources=result.filePaths}return sources.map(source=>ensureAsset(p,source,folder))});
call('asset:paste',(p:Project,bytes:number[],extension:string)=>{const dir=path.join(projectDir(validId(p.id)),'richtext-assets');fs.mkdirSync(dir,{recursive:true});const id=crypto.randomUUID(),name=`${id}.${extension}`;fs.writeFileSync(path.join(dir,name),Buffer.from(bytes));return {id,name,relativePath:`richtext-assets/${name}`,size:bytes.length,mime:`image/${extension}`} as Asset});
call('asset:url',(p:Project,a:Asset)=>{const full=assetPath(p,a);return `file://${full.replace(/\\/g,'/')}`});
call('asset:open',(p:Project,a:Asset)=>shell.openPath(assetPath(p,a)));
call('asset:remove',(p:Project,a:Asset)=>{const file=assetPath(p,a);if(fs.existsSync(file))fs.rmSync(file)});
call('export:project',async(p:Project)=>{const result=await dialog.showSaveDialog(win,{defaultPath:`${p.name}.sjproject`,filters:[{name:'项目包',extensions:['sjproject']}]});if(result.canceled||!result.filePath)return;save(p);const zip=new AdmZip();zip.addFile('project.json',Buffer.from(JSON.stringify({format:'sjproject',version:1,softwareVersion:app.getVersion(),exportedAt:new Date().toISOString(),project:p},null,2)));const dir=projectDir(p.id);if(fs.existsSync(dir))zip.addLocalFolder(dir,'assets');zip.writeZip(result.filePath);return result.filePath});
call('import:inspect',async()=>{const r=await dialog.showOpenDialog(win,{properties:['openFile'],filters:[{name:'项目包',extensions:['sjproject','zip']}]});if(r.canceled)return null;const file=r.filePaths[0];const zip=new AdmZip(file);const entry=zip.getEntry('project.json');if(!entry)throw Error('不支持此项目包结构。旧网页版 ZIP 需提供样本后适配。');const data=JSON.parse(entry.getData().toString('utf8'));if(data.format!=='sjproject'||data.version!==1||!data.project?.id||!data.project?.data)throw Error('项目文件读取失败，请检查文件是否完整');return {file,project:data.project,exportedAt:data.exportedAt,version:data.version,conflict:!!db.prepare('SELECT id FROM projects WHERE id=?').get(data.project.id)}});
call('import:commit',(file:string,mode:'copy'|'overwrite')=>{const zip=new AdmZip(file),manifest=JSON.parse(zip.getEntry('project.json')!.getData().toString('utf8'));const p=manifest.project as Project;validId(p.id);if(mode==='copy')p.id=crypto.randomUUID();const dest=projectDir(p.id);const temp=path.join(root(),'import-'+crypto.randomUUID());fs.mkdirSync(temp,{recursive:true});try{for(const e of zip.getEntries()){if(e.entryName==='project.json'||e.isDirectory)continue;if(!e.entryName.startsWith('assets/'))throw Error('项目包包含无效路径');const rel=e.entryName.slice(7);if(rel.includes('..')||path.isAbsolute(rel))throw Error('项目包包含无效路径');const target=path.resolve(temp,rel);if(!target.startsWith(temp+path.sep))throw Error('项目包包含无效路径');fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,e.getData())}if(mode==='overwrite'&&fs.existsSync(dest))fs.rmSync(dest,{recursive:true});fs.renameSync(temp,dest);return save(p)}finally{if(fs.existsSync(temp))fs.rmSync(temp,{recursive:true,force:true})}});
call('project:copy',(p:Project,withAssets:boolean)=>{const clone:Project=structuredClone(p);clone.id=crypto.randomUUID();clone.name=`${p.name} - 副本`;clone.createdAt=new Date().toISOString();clone.status='编辑中';if(withAssets){fs.cpSync(projectDir(p.id),projectDir(clone.id),{recursive:true})}else{clone.data.images={};clone.data.attachments={};clone.data.videos={};clone.data.richtext=Object.fromEntries(Object.entries(clone.data.richtext).map(([k,v])=>[k,v.replace(/<img[^>]*>/g,'')]))}return save(clone)});
call('project:purge',(p:Project)=>{validId(p.id);db.prepare('DELETE FROM projects WHERE id=?').run(p.id);fs.rmSync(projectDir(p.id),{recursive:true,force:true})});
call('backup:create',()=>makeBackup());call('backup:list',()=>fs.readdirSync(backups()).filter(x=>x.endsWith('.db')).sort().reverse());call('backup:restore',(name:string)=>{if(!/^app-[\w-]+\.db$/.test(name))throw Error('备份文件名无效');const src=path.join(backups(),name);if(!fs.existsSync(src))throw Error('备份不存在');return makeBackup().then(()=>{db.close();fs.copyFileSync(src,path.join(root(),'database','app.db'));db=new Database(path.join(root(),'database','app.db'));db.pragma('journal_mode = WAL');return true})});
call('export:pdf',async(p:Project)=>{const r=await dialog.showSaveDialog(win,{defaultPath:`${p.name}-项目投资资料.pdf`,filters:[{name:'PDF',extensions:['pdf']}]});if(r.canceled||!r.filePath)return;const report=new BrowserWindow({show:false,webPreferences:{sandbox:true}});const html=reportHtml(p);await report.loadURL('data:text/html;charset=utf-8,'+encodeURIComponent(html));const pdf=await report.webContents.printToPDF({pageSize:'A4',printBackground:true,displayHeaderFooter:true,headerTemplate:'<div style="font-size:9px;width:100%;text-align:center">项目投资资料</div>',footerTemplate:`<div style="font-size:9px;width:100%;text-align:center">${escape(p.name)} · ${new Date().toLocaleDateString('zh-CN')} · <span class="pageNumber"></span></div>`});fs.writeFileSync(r.filePath,pdf);report.close();return r.filePath});}
function escape(s:string){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))}
function reportHtml(p:Project){const rows=(obj:Record<string,string>)=>Object.entries(obj).map(([k,v])=>`<tr><th>${escape(k)}</th><td>${escape(v)}</td></tr>`).join('');const table=(title:string,content:string)=>`<h2>${title}</h2><table>${content}</table>`;const imageData=(a:Asset)=>{try{const ext=path.extname(a.relativePath).slice(1);return `data:image/${ext==='jpg'?'jpeg':ext};base64,${fs.readFileSync(assetPath(p,a)).toString('base64')}`}catch{return ''}};let html=table('项目基本信息、场地与电力、车流与竞争',rows(p.data.fields));html+=table('股权结构',p.data.shareholders.map(x=>`<tr><td>${escape(x.name)}</td><td>${escape(x.ratio)}%</td><td>${escape(x.amount)} 万元</td><td>${escape(x.terms)}</td></tr>`).join(''));html+=table('投资构成',p.data.investments.map(x=>`<tr><td>${escape(x.name)}</td><td>${escape(x.amount)} 万元</td><td>${escape(x.tax)}</td><td>${escape(x.range)}</td><td>${escape(x.note)}</td></tr>`).join(''));html+='<h2>现场照片</h2>';for(const [slot,assets] of Object.entries(p.data.images))html+=`<h3>${escape(slot)}</h3>`+assets.map(a=>`<figure><img src="${imageData(a)}"><figcaption>${escape(a.name)} ${escape(a.note||'')}</figcaption></figure>`).join('');html+='<h2>附件清单</h2>'+Object.entries(p.data.attachments).map(([k,v])=>`<p>${escape(k)}：${v.files.map(a=>escape(a.name)).join('、')||'未提供'}</p>`).join('');html+='<h2>视频资料</h2>'+Object.entries(p.data.videos).map(([k,v])=>`<p>${escape(k)}：${escape(v.file?.name||'')} ${escape(v.cloudUrl)}</p>`).join('');html+='<h2>补充说明</h2>'+Object.entries(p.data.richtext).map(([k,v])=>`<h3>${escape(k)}</h3><div>${v.replace(/<script[\s\S]*?<\/script>/gi,'').replace(/project-asset:\/\/[^"']+/g,src=>{try{const u=new URL(src);const full=path.resolve(projectDir(p.id),decodeURIComponent(u.pathname.slice(1)));if(!full.startsWith(projectDir(p.id)+path.sep))return '';const ext=path.extname(full).slice(1);return 'data:image/'+(ext==='jpg'?'jpeg':ext)+';base64,'+fs.readFileSync(full).toString('base64')}catch{return ''}})}</div>`).join('');return `<html><meta charset="utf-8"><style>body{font-family:'Microsoft YaHei','PingFang SC',sans-serif;color:#233;padding:20px;font-size:12px}h1,h2{color:#1767b2}h2{border-bottom:1px solid #ddd;padding:8px 0;break-after:avoid}table{border-collapse:collapse;width:100%;margin:10px 0}td,th{border:1px solid #ccc;padding:6px;vertical-align:top;word-break:break-word}th{width:35%;background:#f4f7fb}tr,figure{break-inside:avoid}img{max-width:100%;max-height:400px}figure{display:inline-block;width:45%;margin:8px}</style><h1>项目投资资料</h1><h2>${escape(p.name)}</h2>${html}</html>`}
if(process.platform==='win32'){app.commandLine.appendSwitch('disable-gpu');app.commandLine.appendSwitch('in-process-gpu')}
if(process.env.PROJECT_MANAGER_TEST_DATA)app.setPath('userData',process.env.PROJECT_MANAGER_TEST_DATA);
protocol.registerSchemesAsPrivileged([{scheme:'project-asset',privileges:{standard:true,secure:true,stream:true,supportFetchAPI:true}}]);
function createWindow(){win=new BrowserWindow({width:1440,height:900,minWidth:1000,minHeight:700,webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false,sandbox:false,webSecurity:true}});if(!app.isPackaged&&process.env.VITE_DEV_SERVER_URL)win.loadURL(process.env.VITE_DEV_SERVER_URL);else win.loadFile(path.join(__dirname,'../dist/index.html'));win.webContents.on('render-process-gone',(_e,d)=>log(`渲染进程异常: ${d.reason}`))}
app.whenReady().then(()=>{try{init();setup();protocol.registerFileProtocol('project-asset',(req,cb)=>{try{const u=new URL(req.url);const id=validId(u.hostname);const relative=decodeURIComponent(u.pathname.slice(1));const full=path.resolve(projectDir(id),relative);if(!full.startsWith(projectDir(id)+path.sep))throw Error('路径无效');cb({path:full})}catch{cb({error:-6})}});createWindow()}catch(e){log(e);dialog.showErrorBox('启动失败','数据库读取失败，请检查本地数据或日志。')}});app.on('activate',()=>{if(BrowserWindow.getAllWindows().length===0)createWindow()});app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});app.on('before-quit',()=>db?.close());
