export type Asset={id:string;name:string;relativePath:string;size:number;mime:string;note?:string;duration?:number};
export type Row=Record<string,string>;
export type ProjectData={fields:Record<string,string>;shareholders:Row[];investments:Row[];images:Record<string,Asset[]>;attachments:Record<string,{checked:boolean;files:Asset[]}>;videos:Record<string,{file?:Asset;cloudUrl:string;code:string}>;richtext:Record<string,string>};
export type Project={id:string;name:string;type:string;city:string;address:string;contact:string;createdAt:string;updatedAt:string;status:'编辑中'|'资料完成'|'已归档'|'回收站';data:ProjectData};
export const imageSlots=[['场站全景','含进出通道与相邻道路开口'],['电力接入点','变压器位、环网柜所在地'],['竞争站点','3km 内主要竞品外观'],['场地进出通道','车道宽度与转弯半径'],['拟建充电区','车位排布与雨棚位置'],['现场其他补充','既有设施铭牌 / 运行指示']] as const;
export const attachmentSlots=[['合资协议 / 股东协议（含治理与退出条款）','建议 PDF 扫描件'],['场地租赁合同或合作意向书','PDF 扫描件'],['土地使用权属证明 / 产权文件','复印件加盖公章'],['供电方案意见书与电力报装受理单','原件扫描'],['设备与工程报价单（含税、含浮动）','Excel + PDF'],['近年财务报表或资信证明（如有）','审计报告优先']] as const;
export const investmentDefaults=['充电设备（充电桩 / 主机）','箱式变压器与高低压柜','电缆与土建施工','雨棚 / 标识 / 照明','监控与平台接入','勘察设计与其他费用','其他（自行填写）'];
export const fieldGroups=[{title:'1.1 项目基本信息',hint:'金额统一填写至「万元」，注明是否含税',fields:[['项目名称','text',true],['项目类型','select:重卡充电站|公共充电站|物流园充电站|其他',true],['所在城市','text',true],['场地详细地址','text',true],['场地面积（㎡）','number'],['可布置充电车位（个）','number'],['对接联系人','text',true],['联系电话','tel',true],['联系邮箱','email'],['提交日期','date',true]]},{title:'1.2 场地与电力条件',hint:'决定工程可行性与隐性成本',fields:[['土地权属性质','select:国有|集体|租赁|其他'],['租赁期限（年）','number'],['年租金（万元/年）','number'],['现有变压器容量（kVA）','number'],['距高压接入点（km）','number'],['是否已有环网柜 / 开闭所','select:已有|需新建|待定'],['电力报装进度','select:未启动|办理中|已完成|待定'],['供电方案预计完成时间','date'],['场地与电力补充说明','textarea']]},{title:'1.3 周边车流与竞争',hint:'车流数据的采集时间与方式请一并注明',fields:[['3km 内竞争站点数（个）','number'],['3km 内竞争枪数（枪）','number'],['周边服务费均价（元/度）','number'],['日均重卡车流（辆/天）','number'],['日均社会车流（辆/天）','number'],['车流采集方式','textarea'],['主要客户群体','textarea']]},{title:'3.2 出资安排与资金计划',fields:[['项目总投资（万元）','number'],['我方出资（万元）','number'],['我方持股比例（%）','number'],['资金来源','select:自有资金|银行贷款|股东出资|其他'],['出资方式与分期计划','textarea'],['退出条款要点 / 反向触发条件','textarea']]},{title:'4.2 收益测算关键假设',hint:'须同时给出目标值与实测值',fields:[['单枪日均充电量 · 目标值（度/枪·天）','number'],['单枪日均充电量 · 实测值（度/枪·天）','number'],['服务费单价 · 拟定（元/度）','number'],['服务费单价 · 周边均价（元/度）','number'],['综合电损率（%）','number'],['购电单价（元/度）','number'],['年租金（万元）','number'],['平台抽佣（%）','number'],['测算回收期（年）','number'],['测算 IRR（%）','number'],['未测算请填写原因','textarea'],['测算口径与假设说明','textarea']]},{title:'6.4 提交信息',fields:[['填表人确认','select:是|否'],['本人姓名','text'],['资料完整度自评','select:资料不完整|基本完整|较完整|完整']]}] as const;
export function emptyData():ProjectData{return {fields:{},shareholders:Array.from({length:4},()=>({name:'',ratio:'',amount:'',terms:''})),investments:investmentDefaults.map(name=>({name,amount:'',tax:'',range:'',note:''})),images:{},attachments:{},videos:{},richtext:{}}}
export function completeness(p:Project){const missing:string[]=[];let total=0;for(const g of fieldGroups)for(const [name,,required] of g.fields)if(required){total++;if(!p.data.fields[name]?.trim())missing.push(name)}for(const [name] of imageSlots.slice(0,3)){total++;if(!p.data.images[name]?.length)missing.push(`${name}照片`)}for(const [name] of attachmentSlots.slice(0,5)){total++;if(!p.data.attachments[name]?.files.length&&!p.data.attachments[name]?.checked)missing.push(name)}for(const name of ['项目总投资（万元）','测算 IRR（%）']){total++;if(!p.data.fields[name]?.trim())missing.push(name)}return {percent:Math.round((1-missing.length/total)*100),missing}}
